### ISSUE TITLE
Uppercase to lowercase for ids and links

### ISSUE THREAD

**Issue by krlklm** [wottpal/kirby-anchor-headings#1]
Is there an option to convert all ids and links to lowercase? If not, this is a feature request. How could i hack this the easiest way until this becomes a feature? Thanks!

**Comment by wottpal** [comment]
Hey @krlklm,
thanks for this good Idea. I've updated the plugin to `0.3.0` where `anchorheadings.id.rules` not only takes regular expressions as before but also callback-functions with the help of PHPs `preg_replace_callback`. In [this](https://stackoverflow.com/a/34420547/1381666) SO answer I've found out how to use this for converting upper- to lowercase. 

But I liked the idea of having lowercase-ids so much that I've added this to the default configuration. So you actually only need to update the plugin and delete all `c::set('anchorheadings.id.rules', ...)` if you had any. See the updated readme and release-page for more information.

Oh and please close this issue if everything is working for you now ;)

Happy Halloween 🎃🧛‍♂️🧟‍♂️

**Comment by krlklm** [comment]
Thanks a lot! Works perfectly now.
